### ISSUE TITLE
Battery status app

### ISSUE THREAD

**Issue by MatthewWilkes** [emfcamp/TiDAL-Firmware#11]
App to show current battery and charging status

Enhancements:
* Log battery level
* Calibrate voltages against time for time remaining estimation

**Comment by andypiper** [comment]
Might be possible to [borrow](https://github.com/pimoroni/pimoroni-pico/blob/main/micropython/examples/badger2040/battery.py) from the Pimoroni Badger? Albeit it's an RP2040 board with an eInk screen so the output format will be different, if the battery uses ADC on this badge then the MicroPython function calls should be similar.

**Comment by craftit** [comment]
I've created a simple battery app here:  https://github.com/emfcamp/TiDAL-Firmware/pull/41
