### ISSUE TITLE
IRQ not working

### ISSUE THREAD

**Issue by MatthewWilkes** [emfcamp/TiDAL-Firmware#15]
The Micropython implementation isn't firing interrupts on pins. Writing C code directly in a micropython function to register handlers also doesn't work. The same code in a non-upy environment does work, so something about the build or setup is breaking interrupts.

**Comment by tomsci** [comment]
@MatthewWilkes am I missing something, or does our version of esp-idf not have the fix from the issue you linked?

**Comment by MatthewWilkes** [comment]
I thought it did? Thought it was merged into 4.4 a few months before release. The issue linked is about interrupts on the 2nd core anyway, and we are using core 1. I only linked to it as a source of small interrupt testing code.

**Comment by tomsci** [comment]
Hmm.... there is a tag called `v4.4` which points to 8153bfe4125e6a608abccf1561fd10285016c90a which seems to be what we're using and _doesn't_ include the fix, but there's a branch called `release/v4.4` which is more recent and _does_. I'll try rebuilding against release/v4.4 and see what happens. (Aside, quite how `git clone --branch v4.4` selected a tag not a branch I won't even attempt to figure out...)

**Comment by tomsci** [comment]
Resolved by #24
