### ISSUE TITLE
Add flashing support to torch app

### ISSUE THREAD

**Issue by tomsci** [emfcamp/TiDAL-Firmware#39]
The default torch app could do with the ability to make the LED flash. I was thinking to make BUTTON_B cycle through various different flash speeds using a `self.periodic(...)` timer.

**Comment by craftit** [comment]
I'll have a look

**Comment by craftit** [comment]
There's a pull request ready for review.  https://github.com/emfcamp/TiDAL-Firmware/pull/40

**Comment by tomsci** [comment]
Resolved by #40
