### ISSUE TITLE
Duck facts app

### ISSUE THREAD

**Issue by andypiper** [emfcamp/TiDAL-Firmware#60]
The [EMF Ducks](https://twitter.com/emfducks) have an API. 

From the [developer site](https://developer.emfcamp.org):

```
Duck fact of the day API: https://03vpefsitf.execute-api.eu-west-1.amazonaws.com/prod/
```

Clearly, this must be available via the badge.

**Comment by bendooks** [comment]
You have been subscribed to duck facts.
Did you know a duckling takes 21 days to hatch
