### ISSUE TITLE
Task switcher OS

### ISSUE THREAD

**Issue by MatthewWilkes** [emfcamp/TiDAL-Firmware#7]
How will users navigate between applications? We probably want a launcher app, how can users get back to it?

**Comment by tomsci** [comment]
Current state of play is:

We have an `App` base class all apps should inherit from, with `on_start()` (called once on app launch) and `on_activate()` (called whenever the app is switched to) plus a `Scheduler` class which implements a `switch_app()` API. The default behaviour of `App` is for `BUTTON_FRONT` to switch back to the app_launcher app (which is currently a very basic text menu).

**Comment by tomsci** [comment]
I think we can close this, the basics are done.
