### ISSUE TITLE
USB HID descriptors identifying as mouse

### ISSUE THREAD

**Issue by tomsci** [emfcamp/TiDAL-Firmware#72]
Had a report of a Dell Latitude which identified the Tidal badge as a mouse (and disabled the trackpad as a result) - it might be the Dell software but we should check our hid descriptors

**Comment by MatthewWilkes** [comment]
We do send a mouse descriptor and the controls are exposed in micropython. I imagined people would make use of them, for example as a mouse jiggler.

**Comment by tomsci** [comment]
Oh, OK. Fair enough then, closing as not a bug :)
