### ISSUE TITLE
Wifi config

### ISSUE THREAD

**Issue by MatthewWilkes** [emfcamp/TiDAL-Firmware#8]
Application to allow users to control the wifi peripheral, allowing search, join and creation of wifi networks, as well as control over enabling/disabling the peripheral.

**Comment by MatthewWilkes** [comment]
Setting up a basic wifi config to allow joining a network easily

**Comment by tomsci** [comment]
We have search and join functionality, since the EMF event doesn't allow custom access points we can probably call it a day there and close this for now?
